### ISSUE TITLE
names for some blocks not showing up in legend

### ISSUE THREAD

**Issue by melteng** [d3plus/d3plus-legend#44]
<img width="1124" alt="screenshot 2016-09-29 18 52 23" src="https://cloud.githubusercontent.com/assets/8160651/18975133/f5cf3dfa-8675-11e6-86f7-d22b7ea74747.png">
<img width="1123" alt="screenshot 2016-09-29 18 52 31" src="https://cloud.githubusercontent.com/assets/8160651/18975132/f5ce71ea-8675-11e6-843c-aa4388b32027.png">

**Comment by davelandry** [comment]
I'm going to need to dig a bit deeper to fix this one. It's working in my test environment:

<img width="965" alt="screen shot 2016-10-03 at 4 04 53 pm" src="https://cloud.githubusercontent.com/assets/1847581/19052040/4af0c65e-8983-11e6-9f98-78a30de2a703.png">
