### ISSUE TITLE
label function for bars works differently than legend?

### ISSUE THREAD

**Issue by jspeis** [d3plus/d3plus-legend#57]
label function appears to work different on the bars in the bar chart versus the legend below:

![screen shot 2017-06-12 at 9 11 37 am](https://user-images.githubusercontent.com/87581/27035395-2d9aa3e4-4f4f-11e7-943b-f85f0d85a0b3.png)

```          label: d => `${lookup[d["Living Arrangement"]]} in ${d.kind}` ```

I would have expected the labeling to work the same so that the same logic could be reused (maybe even the object to the legend should also contain a key in the object that is a values array that could be useful for adding summary stats in legend tooltips?)

**Comment by davelandry** [comment]
@jspeis in your example case, there are 2 different "Living Arrangement" values for each color, so while that label logic is accurate for each bar, it does not represent the correct label for each color. `d["Living Arrangement"]` for the legend colors is an array with each value, so you are seeing the array concatenated with commas. In this case, you should explicitly be passing a different label function to the `legendConfig`:

```js
legendConfig: {
  label: d => d.kind
}
```
