### ISSUE TITLE
setting label color for a ColorScale

### ISSUE THREAD

**Issue by alexandersimoes** [d3plus/d3plus-legend#59]
Having trouble setting the text color for a color scale legend. Here's my config below:

```js
colorScaleConfig: {
    color: COLORS_GRADIENT,
    scale: "jenks",
    shapeConfig: {
      fill: "#979797",
      fontColor: "white",
      labelConfig: {
        fontColor: "white", // this doesn't work!
      },
      stroke: "#979797"
    },
    tickSize: 0,
    titleConfig: {
      textTransform: "uppercase"
    }
}
```

And here is the rendered output:

<img width="667" alt="screen shot 2017-12-15 at 5 17 53 pm" src="https://user-images.githubusercontent.com/252276/34062682-ee3eee6c-e1bb-11e7-8ee2-491acbfda5b7.png">

**Comment by davelandry** [comment]
@alexandersimoes the [ColorScale](http://d3plus.org/docs/#ColorScale) class does not have a shapeConfig method, it has separate configs for the [Axis](http://d3plus.org/docs/#Axis) class used to display the text ([axisConfig](http://d3plus.org/docs/#ColorScale.axisConfig)) and the [Rect](http://d3plus.org/docs/#Rect) class used to draw the color breaks ([rectConfig](http://d3plus.org/docs/#ColorScale.rectConfig)). This config should work:

```js
colorScaleConfig: {
  axisConfig: {
    shapeConfig: {
      labelConfig: {
        fontColor: "white"
      },
      stroke: "#979797"
    }
  },
  color: COLORS_GRADIENT,
  scale: "jenks",
  tickSize: 0,
  titleConfig: {
    textTransform: "uppercase"
  }
}
```

Additionally, I've created an example showing this behavior: http://d3plus.org/examples/d3plus-legend/colorScale-dark/
